### ISSUE TITLE
C-a/C-e for Home/End

### ISSUE THREAD

**Issue by gergelypolonkai** [bbatsov/guru-mode#11]
Most text editors have the `beginning-of-line`/`end-of-line` functionality bound to the <kbd>Home</kbd> and <kbd>End</kbd> keys. Shouldn’t they be used in `guru-mode`, too, instead of `beginning-of-buffer`/`end-of-buffer` (i.e. <kbd>C-a</kbd>/<kbd>C-e</kbd> instead of <kbd>M-&lt;</kbd>/<kbd>M-&gt;</kbd>)?

**Comment by J3RN** [comment]
Seconded. Testing in Emacs 25 on Debian 9, `Home` and `End` behave correspondingly to `C-a` and `C-e`, respectively, not `M-<` and `M->`. Since this looks like it would be an easy fix, I'll make it presently.
