### ISSUE TITLE
How to add new keys to the affected list?

### ISSUE THREAD

**Issue by ThibautVerron** [bbatsov/guru-mode#7]
Hi,

It would be nice if we could add more keys to `guru-affected-bindings-list`, but it doesn't seem to be possible at the moment. I guess putting the `dolist` initializing the keymap into a `defun` and requiring that the user calls that function after changing the variable (or a mix&match with `custom`) would do it, but I don't understand the code well enough to do it myself.

Is the package dependent on that dolist being evaluated only once, at load time?

**Comment by bbatsov** [comment]
5 years later I remembered about this ticket. Sorry about the long wait!
